### ISSUE TITLE
Please add this to hasura community folder

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#1]
Hi @elitan,
It's awesome example. Please add this to community folder as other guys suggest in this issue: [hasura/graphql-engine#1446](https://github.com/hasura/graphql-engine/issues/1446)

Thanks man

**Comment by elitan** [comment]
I do not think this repo should live inside the hasura/graphql-engine. Better for it to live here. What do you think?

**Comment by mnlbox** [comment]
I think it's useful for other too and if it's include in community folder in hasura/graphql-engine repo more user can access it or add this link somewhere in docs or community folder ReadMe.md here:
https://github.com/hasura/graphql-engine/blob/master/community/README.md

**Comment by elitan** [comment]
This repo will live here

**Comment by mnlbox** [comment]
@elitan It's OK so please introduce it in Related README.md I think if more people know this project and community grow we can do more work. :wink:
