### ISSUE TITLE
Switch to Graphqurl

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#12]
Hi @elitan 
I suggest to switch from [graphql-request](https://github.com/prisma/graphql-request) to [graphqurl](https://github.com/hasura/graphqurl) because it's more active and it's introduce officially from Hasura :heart:
I think it's better to support our community available tools. :wink: 

I'm talking about this file:
https://github.com/elitan/hasura-backend-plus/blob/master/src/graphql-client.js

**Comment by elitan** [comment]
Sounds like a good idea!

**Comment by elitan** [comment]
graphqurl is more for CLI. graphql-request is a better fit for node js projects like this where we can initiate a GraphQL client with headers.
