### ISSUE TITLE
Please add some handy mutation

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#15]
Please add some handy mutation for general task like this:
https://github.com/DevSpeak/hasura-simple-auth/blob/master/server.js

**Comment by Pomazan-Bogdan** [comment]
general, are there any such things?

**Comment by mnlbox** [comment]
No, Now you need use [Auth](https://github.com/elitan/hasura-backend-plus#auth) API for user management tasks. More info about these api exist here:
https://github.com/elitan/hasura-backend-plus/issues/5

**Comment by elitan** [comment]
You can also mutate the user data in the database directly. Either through Hasura or in the Postgres database direct.

Or maybe I am misunderstanding this issue. Could you perhaps provide an example / use-case?

**Comment by mnlbox** [comment]
This is not just about CRUD for example for `login` we need pass username, password and got token as a return value. It contain many login like: https://github.com/elitan/hasura-backend-plus/blob/8adb4e84bfdd5de5dd7cdc4d2971bf5a5e11134c/src/auth/auth.js#L257 and we just want call a mutation for login. It's a simple wrapper around exist REST api for Auth:
```
/register
/activate-account
/sign-in
/refetch-token
/new-password
```
Really same as: https://github.com/DevSpeak/hasura-simple-auth

**Comment by elitan** [comment]
I am not sure I understand you correctly. 

This is how I use ex. sign-in

```
    try {
      req = await axios.post(`${HBP_ENDPOINT}/auth/sign-in`, {
        email,
        password,
      });
    } catch (e) {
     //handle error
    }

    Auth.setSession(req.data);
```

I do not use HB+ via Hasura or GraphQL

**Comment by elitan** [comment]
https://github.com/nhost/nhost-js-sdk
