### ISSUE TITLE
Add react-admin admin GUI for user management tasks

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#2]
@elitan Now [Hasura support react-admin](https://github.com/hasura/graphql-engine/issues/783) I think it can be useful if this `backed-plus` can support user management task (create user, role, reset users password, ...) thought a GUI admin panel.

What is your opinion?

**Comment by elitan** [comment]
I agree. A GUI would be helpful.

However you can already do most of in the Hasura console. You can:
- Create users
- Delete users
- Edit users (email, role etc)

You can not reset user password in the Hasura Console with this repo tho.

**Comment by mnlbox** [comment]
@elitan Thanks man, so are you any plan for add any GUI to this repo?

**Comment by elitan** [comment]
Exactly. 

A GUI for managing users and storage should probably live in another repo. I currently do not have any short term plans on doing that.
