### ISSUE TITLE
Change name of hasura-backend-plus?

### ISSUE THREAD

**Issue by elitan** [elitan/hasura-backend-plus#20]
Right now the name `hasura-backend-plus` is a long name, not really unique and it does not feel it has its own 'soul'.

My idea is to change the repo name to something easier, smaller and catchier with just a single name? Like:

- yeasura
- blace
- moritter

or something similar.

My idea is to also add a js sdk. Much like `firebase-js-sdk` that will handle auth and storage more easiely. Like:

```
    const upload_res = await <reponame>.upload('product-images/', [this.image_upload], (progressEvent) => {
      console.log('new progress event');
      console.log(progressEvent);
    });
```

1. Thoughts on the idea to change the repo name?
2. Any name suggestions? (optional)

**Comment by mnlbox** [comment]
Oh man. I like `hasura-backend-plus` and it's abbreviation `HB+`. One of the things that attract me to this project is it's name. :wink:

**Comment by elitan** [comment]
We keep the name for now :)
