### ISSUE TITLE
Account creation limits

### ISSUE THREAD

**Issue by elitan** [elitan/hasura-backend-plus#22]
Firebase has: 

Operation | Limit
-- | --
New account creation | 100 accounts/IP address/hour
Account deletion | 10 accounts/second

https://firebase.google.com/docs/auth/limits

We should implement something similar.

**Comment by mnlbox** [comment]
Can you explain more?

**Comment by elitan** [comment]
hb+ should not allow to create more than 100 (variable) accounts per IP address. This is a way to mitigate spammers.

**Comment by mnlbox** [comment]
@elitan we also need login limit to prevent brute force attack.
For example block account for 5 minutes after 3 wrong login try or use captcha or other approach.

**Comment by mnlbox** [comment]
Maybe some captcha solution or example also can be useful here.

**Comment by elitan** [comment]
I think this is better handled by a web server. Ex:

https://caddyserver.com/docs/http.ratelimit

https://github.com/xuqingfeng/caddy-rate-limit/blob/master/README.md
