### ISSUE TITLE
add USER_FIELDS example

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#3]
Hi @elitan,
Thanks for this awesome repo, Can you explain how we can use USER_FIELDS for add custom user fields?
I can't find any example or note in ReadMe.md file.

**Comment by elitan** [comment]
Definitely. As you probably have found out by now the project is not very well documented and early in the development process.

Let me give you some quick hints here before I add it to the README.

If you have some specific fields on your users that you also want to have as a JWT claim you can specify those user fields in the `USER_FIELDS` env var. 

So lets say you have a user table like:

- id
- email
- password
- role
- company_id

and you want to include the `company_id` as a JWT claim. You can specify `USER_FIELDS=company_id`.

Then you will have a JWT a little something like this:

```
{
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": [
      "company_admin"
    ],
    "x-hasura-default-role": "company_admin",
    "x-hasura-user-id": "3",
    "x-hasura-company-id": "1" <------ THERE WE GO :)
  },
  "iat": 1549526843,
  "exp": 1549527743
}
```

This enables you to make permissions using `x-hasura-company-id` for insert/select/update/delete in on tables in your Hasura console. Like this: `{"seller_company_id":{"_eq":"X-HASURA-COMPANY-ID"}}`

It also enables you to write permission rules for the storage endpoint in this repo. Here is an example:
https://github.com/elitan/hasura-backend-plus/blob/master/src/storage/storage-tools.js#L16

**Comment by mnlbox** [comment]
Thanks man. It can very useful based on use case that you tell. :pray:

**Comment by mnlbox** [comment]
@elitan What about `"https://hasura.io/jwt/claims"` can we need to modify it based on my endpoint url or it's some convention or special key?

**Comment by elitan** [comment]
https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html#the-spec

```
The https://hasura.io/jwt/claims is the custom namespace where all Hasura specific claims have to be present. This value can be configured in the JWT config while starting the server.
```

I would suggest to keep it at default. So you do not need to edit anything.
