### ISSUE TITLE
Login try limit

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#30]
Hi @elitan ,
We need some login try limitation solution. Something like #22 but for login.

Some approach:
1. Block user for X minute after Y unsuccessful login try.
2. Show captcha image after X unsuccessful login try.

We also need some new environment variable for this X, Y, ...
We also need implement this for both traditional and 2FA login mechanism after merge #29

**Comment by mnlbox** [comment]
I think it's an important feature in production.
Are you any plan for add this?

**Comment by elitan** [comment]
Yes planning to add it. No time estimate tho.

**Comment by elitan** [comment]
I think this is better handled by a web server. Ex:

https://caddyserver.com/docs/http.ratelimit

https://github.com/xuqingfeng/caddy-rate-limit/blob/master/README.md
