### ISSUE TITLE
Add new environment varaible to enable/disable auth or storage

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#31]
@elitan Now someone don't need auth because for example they are using Auth0 (For example like @marcokoeppel-merck and his fork https://github.com/toastedtoast/hasura-storage) or don't need storage I think maybe it's better to ability to disable `/auth` or `/storage` totally with an environment variable.

@marcokoeppel-merck can you do this as a PR?
Thanks

**Comment by toastedtoast** [comment]
Hi, 

I am still very much experimenting with my fork and at least in my scenario just disabling the auth part does not do the job so I decided to work in seperate environment until I am confident with the approach.

**Comment by elitan** [comment]
@toastedtoast Nice, you are welcome to do a PR anytime if you want. Let me know if you need any assistent.
