### ISSUE TITLE
hasura-backend-plus + react-admin

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [elitan/hasura-backend-plus#34]
Hey.
I have a question, is it possible if I am using react-admin to use your package for authorization there?

**Comment by elitan** [comment]
I don't have any experience with react-admin so I don't know. Maybe if you have any specific question or obstacle related ro react-admin and hasura-backend-plus I could help you.

**Comment by Pomazan-Bogdan** [comment]
I understand that you need the ability to connect your package as an authProvider according to the documentation:
https://marmelab.com/react-admin/Authentication.html

Can you see briefly, do you see any possible problems?

**Comment by elitan** [comment]
It seems to be pretty straight forward. 

I am developing a js sdk for hasura-backend-plus and it might give you some insight:

https://github.com/nhost/nhost-js-sdk/blob/master/index.js#L27

**Comment by elitan** [comment]
Really I think you can just edit the `https://mydomain.com/authenticate` with your `auth/login` link for hasura backend plus, and save what you want in localStorage of the data you get back
