### ISSUE TITLE
Req: Basic Example

### ISSUE THREAD

**Issue by thebetterjort** [elitan/hasura-backend-plus#39]
I'm looking for a basic example of a file upload from react to hasura backend (minio).

**Comment by elitan** [comment]
Maybe this can help you? https://github.com/nhost/nhost-js-sdk

**Comment by elitan** [comment]
Eventually I will have examples here: https://github.com/nhost/react-hasura-nhost-example-app

**Comment by elitan** [comment]
https://github.com/nhost/nhost-js-sdk is going to be the place to look for examples to handle client side interaction with HBP.
