### ISSUE TITLE
Two step (factor) authentication

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#4]
Hi @elitan ,
I think two step (factor) authentication can be very useful for many applications. I recently implement this in LoopBack based on below article:
https://jordankasper.com/two-factor-authentication-with-loopback/
and use this library:
https://github.com/speakeasyjs/speakeasy

Later I see this library: https://passwordless.net/

For testing purpose I think we need print 2FA code on console and a setting option for example called `send 2FA code by:` to select gateway for send 2FA code (for example we can suggest some option here: send 2FA code through mail plugin, web hook call, sms, ...)

I think this library is more better than other thinking
https://github.com/yeojz/otplib

Lets talk about this here :wink:

**Comment by elitan** [comment]
Agree. Some kind of 2FA would be nice.

I have to do some read-up on existing technologies and see which one could be implemented for this project.

**Comment by mnlbox** [comment]
@elitan Thanks man :wink:

**Comment by elitan** [comment]
Let us keep this discusssion in #16
