### ISSUE TITLE
Please use "GET" for /activate-account

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#40]
Hi @elitan,
It seems you are changing activate account from `GET` to `POST`.
Let's discuss about it in related commit:
 https://github.com/elitan/hasura-backend-plus/commit/cca72e8285c482529319ae6b94bb6e3a67fde528#diff-0d0de5d9ddbfa61dbbb85bd82bc412bb

**Comment by elitan** [comment]
My initial though was that the app needs to handle the front-end.

- Send a verification email with the link to your own front-end (ex: `app.example.com/verify?code=123321`)

- The `/verify` view grabs the `code` parameter and performs a request to HBP.

- If OK, redirect. If not. notify user.

Or, we could changing the method to `GET` and add a envvar to allow redirection of the user.

**Comment by elitan** [comment]
we'll keep `POST` for now.
