### ISSUE TITLE
Add 'get user' endpoint

### ISSUE THREAD

**Issue by MarcelloTheArcane** [elitan/hasura-backend-plus#41]
Great project! I'm getting started with integrating this (via nhost) to Nuxt.js and have come across an issue.

I'm using the default [`@nuxtjs/auth`](https://auth.nuxtjs.org/) module, which requires an endpoint to fetch user data:

```js
auth: {
  strategies: {
    local: {
      endpoints: {
        login: { url: '<url>/auth/login', method: 'post', propertyName: 'token' },
        logout: false,
        user: { url: '<url>/auth/user', method: 'get', propertyName: 'user' }
      },
    }
  }
}
```

the `user` endpoint requires a response similar to this:

```json
{
  "user": {
    <user_data>
  }
}
```

Would it be possible to add an endpoint that runs a query like this?

```graphql
query user($username: String!) {
  users(where: {username: {_eq: $username}}) {
    username
    id
    created_at
  }
}
```

**Comment by elitan** [comment]
Thanks. Hope you are finding the service helpful! 👍

Sure, will `@nuxtjs/auth` do the GET request to `/user` with the jwt_token included as an auth header? 
Maybe you have an example of a request that your current app tries to do?

Also, `@nuxtjs/auth` does not seem to handle refetch tokens directly. Do you use something like this [motia/nuxt-auth-refresh](https://github.com/motia/nuxt-auth-refresh) to handle it?

**Comment by MarcelloTheArcane** [comment]
@elitan Here's what the request looks like (copied from the browser) - so it looks like the token is included in the `Authorization` header.

```bash
curl 'https://backend-xxxxx.nhost.io/auth/user' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Authorization: Bearer <token>'
```

I haven't ever used refetch tokens before, so we'll cross that bridge when I get to it! Thanks for the `nuxt-auth-refresh` link, I'll check it out.

**Comment by elitan** [comment]
Got it. I'll push an update soon.

**Comment by elitan** [comment]
What do you think of: https://github.com/elitan/hasura-backend-plus/pull/43

**Comment by MarcelloTheArcane** [comment]
@elitan #43 looks good to me

**Comment by MarcelloTheArcane** [comment]
@elitan Will this be accessible with [nhost.io](https://nhost.io)?

**Comment by elitan** [comment]
Sorry, missed this. Yes, I'll release it today for new projects.

If you want to upgrade an existing project with this feature let me know (either via Discord or email)

https://discordapp.com/invite/9V7Qb2U
johan@nhost.io
