### ISSUE TITLE
How to access other table schemas?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [elitan/hasura-backend-plus#51]
This is probably a question for Hasura, but I can't seem to find anything on the docs about it.

Is there a way of querying the other tables here? I'd like to set up a duplicate of the `public` database for a testing environment.

![image](https://user-images.githubusercontent.com/21159570/65152265-86af7d80-da1f-11e9-9b42-cb97af7050bd.png)

I assume it would be either a custom header or a different URL.

**Comment by elitan** [comment]
It does not seem to be possible yet:
https://github.com/hasura/graphql-engine/issues/1416

**Comment by elitan** [comment]
![hasura-different-schema](https://user-images.githubusercontent.com/331818/65938700-fe1fdc80-e423-11e9-8f68-f16af8f6b996.gif)

Look at this. Maybe this could help you?

**Comment by MarcelloTheArcane** [comment]
That's it! Awesome

**Comment by elitan** [comment]
> That's it! Awesome!
> 
> Now I need to figure out how to clone all my tables to the dev schema 😀

You should be able to do that with a postgresql client, with some minor tweaking.

I am not sure if it's a good idea to have dev/stage/production in different schemas like this. I think it's better to just have different 'projects' completely.
