### ISSUE TITLE
clear refresh tokens

### ISSUE THREAD

**Issue by tafelito** [elitan/hasura-backend-plus#60]
when do you clear the refresh tokens in the db? Shouldn't it be done when the user logouts?

**Comment by elitan** [comment]
Yes, there are two ways to logout.

1. `/auth/logout` clears the cookie. Other devices (for the same user) can still be logged in.
2. `/auth/logout-all` Deletes all refresh tokens (https://github.com/elitan/hasura-backend-plus/blob/master/src/auth/auth.js#L169)

**Comment by tafelito** [comment]
but if you juts logout it will clear the cookie on the client, but it won't clear the refresh token in the db

so if I login/logout multiple times, it will create as many refresh tokens as I login

**Comment by elitan** [comment]
Correct. You might want to put up a cron job delete expired refetch tokens.

**Comment by tafelito** [comment]
yeah that's what I was thinking. Or maybe delete the token received on logout could be another option

Anyway, thanks for the response
