### ISSUE TITLE
/storage/fn/get-download-url/* returns empty object

### ISSUE THREAD

**Issue by MarcelloTheArcane** [elitan/hasura-backend-plus#70]
I assume the `/fn/get-download-url/*` endpoint [here](https://github.com/elitan/hasura-backend-plus/blob/master/src/storage/storage.js#L64) is intended to provide an image url that can be used in an html `<img>` tag.

I have managed to download the image blob with the [`/file/*` endpoint](https://github.com/elitan/hasura-backend-plus/blob/master/src/storage/storage.js#L136) and convert it to a data url, but it would be nicer to get a simple URL!

Any ideas why I am not getting the token specified [here](https://github.com/elitan/hasura-backend-plus/blob/master/src/storage/storage.js#L97)?

**Comment by elitan** [comment]
This was because the file got uploaded throught S3/Minio directly. 

`/fn/get-download-url/*` endpoint should generate metadata on the fly if not already present.
