### ISSUE TITLE
secret_token expiry date is set to current timestamp

### ISSUE THREAD

**Issue by msojda** [elitan/hasura-backend-plus#75]
Hi,

In the /auth/local/register endpoint you're not incrementing the `secret_token_expires_at` field which results in this field being set to the current timestamp.

This means users cannot activate their accounts because secret token is always expired.

**Comment by elitan** [comment]
Before you send your activation e-mail you should update the `secret_token_expires_at` value to fit your apps need.

**Comment by MarcelloTheArcane** [comment]
@elitan Is there an endpoint to update the `secret_token_expires_at`? It's used for changing the password too.

**Comment by elitan** [comment]
No

You should do that using server side code (ex a cloud function) with admin
access.
