### ISSUE TITLE
Should schema_name be included here?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [elitan/hasura-backend-plus#81]
Should this line include the `schema_name`?

https://github.com/elitan/hasura-backend-plus/blob/01e6b1b5f8ae4a6fd43c484ec27169a2ccbc9138/src/auth/local.js#L237

Surely the GraphQL response is always `user_accounts` because you alias it in the query:

https://github.com/elitan/hasura-backend-plus/blob/01e6b1b5f8ae4a6fd43c484ec27169a2ccbc9138/src/auth/local.js#L201

**Comment by mnlbox** [comment]
Hi @MarcelloTheArcane,
If you want to store user information in separate schema (for example `user management` or `membership` or ...) then you need this.
If you want store user informations and tables in `public` schema just leave it as default.
