### ISSUE TITLE
NHost.io related, Predictable pricing and Multi Tenant

### ISSUE THREAD

**Issue by meteorsnows** [elitan/hasura-backend-plus#82]
Hi, 
Could I request a similar guide like below, to able to host dedicated server on NHost.io for every 1k customer etc.

[Multi Tenant](https://medium.zenika.com/building-a-multi-tenant-application-with-prisma-11bf890304d6?gi=8000dc8892a6)

**Comment by elitan** [comment]
Will do. ETA 4 days

**Comment by meteorsnows** [comment]
Great, can slowly take your time. 
It would be great comparison to serverless for huge traffic site...that people browse all day like YouTube, Reddit

**Comment by elitan** [comment]
https://github.com/hasura/graphql-engine/issues/2836

Which one of alternative [1,2,3] are you currently considering?

I do not have any experience with 1 and 2. 3 I do and could write a blog post about.

Maybe you could describe your use case a bit more. If you don't want to write here, write to me personally at johan@nhost.io.

**Comment by meteorsnows** [comment]
I think I am prefer 3 or 2. 
Thanks for linking me to the #2836

**Comment by elitan** [comment]
Awesome. I made a blog post on how to approach the building of a multi-tenant application with Nhost and Hasura with the same backend (3):

https://blog.nhost.io/building-a-multi-tenant-application-with-nhost-and-hasura/

I published it right with the essential information. I'll be updating the post in the coming weeks.
